# Generated by Django 6.0.4 on 2026-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade_level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Junior High', 'Junior High'), ('Senior High', 'Senior High')], default='Elementary', max_length=50),
        ),
    ]
