# Generated by Django 5.2.15 on 2026-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userstars'),
        ('topics', '0004_update_post_testing_grade_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_topics',
            field=models.ManyToManyField(blank=True, help_text='Topics this instructor is allowed to manage', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level_max',
            field=models.IntegerField(blank=True, help_text='Maximum grade level the instructor can work with', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level_min',
            field=models.IntegerField(blank=True, help_text='Minimum grade level the instructor can work with', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instructional_scope',
            field=models.CharField(blank=True, default='', help_text="E.g. 'Elementary Mathematics Specialist'", max_length=200),
        ),
    ]
