# Generated by Django 6.0.4 on 2026-06-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_progress', '0002_unlockedachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='gamified_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
