# Generated by Django 6.0.4 on 2026-06-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0004_alter_question_choice_a_alter_question_choice_b_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamifiedModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Unique identifier used by frontend and session cache (e.g., 'double-xp')", unique=True)),
                ('modifier_type', models.CharField(choices=[('SCORE_BOOST', 'Score Multiplier'), ('STREAK_SHIELD', 'Streak Protection')], max_length=20)),
                ('multiplier_value', models.FloatField(default=1.0, help_text='Multiplier applied to points (e.g., 1.5, 2.0). Ignore if type is a shield.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playthrough.gamifiedmodifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Inventories',
                'unique_together': {('user', 'modifier')},
            },
        ),
    ]
