# Generated by Django 5.2.15 on 2026-06-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0006_playthroughsession'),
        ('topics', '0002_alter_topic_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLogArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('avg_difficulty', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='playthroughsession',
            new_name='playthrough_user_id_d1d5e2_idx',
            old_name='playthrough_user_topic_idx',
        ),
        migrations.AlterField(
            model_name='gamifiedmodifier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playthroughsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userskillprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='playthroughsession',
            index=models.Index(fields=['updated_at'], name='playthrough_updated_1355cf_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='playthrough_topic_i_48b1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='responselog',
            index=models.Index(fields=['user', 'timestamp'], name='playthrough_user_id_7f9339_idx'),
        ),
        migrations.AddIndex(
            model_name='responselog',
            index=models.Index(fields=['domain', 'timestamp'], name='playthrough_domain_94f06b_idx'),
        ),
        migrations.AddIndex(
            model_name='userinventory',
            index=models.Index(fields=['user', 'quantity'], name='playthrough_user_id_39d9f6_idx'),
        ),
        migrations.AddField(
            model_name='domainrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responselogarchive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='domainrating',
            index=models.Index(fields=['user', 'domain_name'], name='playthrough_user_id_c7101d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domainrating',
            unique_together={('user', 'domain_name')},
        ),
        migrations.AddIndex(
            model_name='responselogarchive',
            index=models.Index(fields=['user', 'date'], name='playthrough_user_id_62e0f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responselogarchive',
            unique_together={('user', 'domain', 'date')},
        ),
    ]
