# Generated by Django 5.2.15 on 2026-06-22 11:02

from django.db import migrations


def migrate_skill_profiles_to_domain_ratings(apps, schema_editor):
    """
    Data migration: Copy existing UserSkillProfile column values into
    DomainRating rows.
    """
    UserSkillProfile = apps.get_model('playthrough', 'UserSkillProfile')
    DomainRating = apps.get_model('playthrough', 'DomainRating')
    
    domain_field_map = {
        'Algebra': 'algebra_rating',
        'Arithmetic': 'arithmetic_rating',
        'Geometry': 'geometry_rating',
        'Statistics': 'statistics_rating',
        'Trigonometry': 'trigonometry_rating',
    }
    
    migrated_count = 0
    for profile in UserSkillProfile.objects.all():
        for domain_name, field_name in domain_field_map.items():
            rating_value = getattr(profile, field_name)
            if rating_value != 1.0:  # Only create rows for non-default values
                DomainRating.objects.create(
                    user=profile.user,
                    domain_name=domain_name,
                    rating=rating_value
                )
                migrated_count += 1
    
    print(f"Migrated {migrated_count} DomainRating rows from {UserSkillProfile.objects.count()} UserSkillProfile records.")


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0007_domainrating_responselogarchive_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_skill_profiles_to_domain_ratings, migrations.RunPython.noop),
    ]