# Generated by Django 5.2.15 on 2026-06-22 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0008_migrate_skill_profiles_to_domain_ratings'),
        ('topics', '0002_alter_topic_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playthroughsession',
            unique_together={('user', 'topic')},
        ),
    ]
