# Generated by Django 5.2.15 on 2026-06-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0009_alter_playthroughsession_unique_together'),
        ('topics', '0002_alter_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('KHAN_ACADEMY', 'Khan Academy'), ('PHET', 'PhET Simulation'), ('DESMOS', 'Desmos Activity'), ('YOUTUBE', 'YouTube Video'), ('CK12', 'CK-12 Lesson')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('embed_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='topics.topic')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['topic', 'grade_level', 'order'], name='playthrough_topic_i_151b3b_idx')],
            },
        ),
    ]
