# Generated by Django 5.2.15 on 2026-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0010_learningresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_solution',
            field=models.TextField(default='No solution provided', help_text='Step-by-step solution for the question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.FloatField(help_text='Difficulty rating: 1.0=Novice, 2.0=Intermediate, 3.0=Advanced'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade_level',
            field=models.IntegerField(help_text='Grade level (1-10, where 1-6 is Elementary and 7-10 is Junior High)'),
        ),
    ]
