# Generated by Django 5.2.15 on 2026-06-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0009_add_question_metadata'),
        ('playthrough', '0011_question_question_solution_alter_question_difficulty_and_more'),
    ]

    operations = [
    ]
