# Generated by Django 5.2.15 on 2026-07-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0012_merge_20260624_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Cost in Stars')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this item is currently available in the shop')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='playthrough.gamifiedmodifier')),
            ],
            options={
                'verbose_name_plural': 'Shop Items',
            },
        ),
    ]
