# Generated by Django 5.2.15 on 2026-07-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0013_shopitem'),
    ]

    operations = [
        # Add is_verified field to Question
        migrations.AddField(
            model_name='question',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether this question has been verified as correct by an instructor or admin"),
        ),
        # Create QuestionChangeRequest model
        migrations.CreateModel(
            name='QuestionChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', 'Add Question'), ('edit', 'Edit Question'), ('delete', 'Delete Question')], max_length=10)),
                ('proposed_data', models.JSONField(help_text='The proposed question data as a JSON object')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='playthrough.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to='auth.user')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_change_requests', to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]