# Generated by Django 5.2.15 on 2026-07-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0014_add_question_change_request_and_verified'),
        ('topics', '0004_update_post_testing_grade_ranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(help_text='Grade level (1-10) this lesson is designed for')),
                ('order', models.IntegerField(default=0, help_text='Display order within the topic/grade')),
                ('title', models.CharField(max_length=200)),
                ('objectives', models.JSONField(help_text='List of learning objectives (array of strings)')),
                ('example', models.TextField(help_text='Example problem for this lesson')),
                ('tip', models.TextField(help_text='Helpful tip for students')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='topics.topic')),
            ],
            options={
                'ordering': ['grade_level', 'order'],
                'indexes': [models.Index(fields=['topic', 'grade_level', 'order'], name='playthrough_topic_i_2d59e8_idx')],
                'unique_together': {('topic', 'grade_level', 'order')},
            },
        ),
    ]
