# Generated by Django 5.2.15 on 2026-07-13 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playthrough', '0016_add_lesson_change_request'),
        ('topics', '0005_add_topic_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text="Unique identifier matching the generator method (e.g., 'arith_01')", max_length=20, unique=True)),
                ('domain', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Statistics', 'Statistics'), ('Trigonometry', 'Trigonometry')], max_length=20)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Basic Addition')", max_length=100)),
                ('template_text', models.TextField(help_text="Template with {placeholder} variables (e.g., 'Calculate: {a} + {b}')")),
                ('solution_template', models.TextField(help_text='Step-by-step solution with {placeholder} variables')),
                ('base_difficulty', models.CharField(choices=[('Novice', 'Novice (1.0)'), ('Intermediate', 'Intermediate (2.0)'), ('Advanced', 'Advanced (3.0)'), ('Expert', 'Expert (4.0)')], max_length=20)),
                ('is_word_problem', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this template has been verified by an instructor')),
                ('is_implemented', models.BooleanField(default=True, help_text='Whether a developer has written the generator code. False for instructor-requested templates awaiting implementation.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is actively generating questions. Set to False when retired.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'template_id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', 'Add Template'), ('edit', 'Edit Template'), ('delete', 'Delete Template')], max_length=10)),
                ('proposed_data', models.JSONField(help_text="The proposed template data as a JSON object. For 'add': {domain, display_name, template_text, solution_template, base_difficulty, is_word_problem, rationale, sample_numbers}. For 'edit': {template_id, reason, ...changed fields}. For 'delete': {template_id, reason}.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='template_id',
            field=models.CharField(blank=True, help_text="Links this question to a QuestionTemplate (e.g., 'arith_01', 'alg_05'). Null for imported/non-template questions.", max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['template_id'], name='playthrough_templat_4bed14_idx'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatechangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_template_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatechangerequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_template_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatechangerequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='playthrough.questiontemplate'),
        ),
    ]
