# Generated by Django 6.0.4 on 2026-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Algebra', 'Algebra'), ('Geometry', 'Geometry'), ('Trigonometry', 'Trigonometry'), ('Statistics', 'Statistics')], max_length=100)),
                ('grade_level', models.CharField(choices=[('Elementary', 'Elementary'), ('Junior High', 'Junior High'), ('Senior High', 'Senior High')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
