# Generated by Django 5.2.15 on 2026-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='topic',
            name='grade_level_max',
            field=models.IntegerField(default=10, help_text='Maximum grade level (1-10)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade_level_min',
            field=models.IntegerField(default=1, help_text='Minimum grade level (1-10)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Number Sense and Place Value', 'Number Sense and Place Value'), ('Fractions, Decimals, and Percentages', 'Fractions, Decimals, and Percentages'), ('Ratios and Proportional Reasoning', 'Ratios and Proportional Reasoning'), ('Algebra and Algebraic Expressions', 'Algebra and Algebraic Expressions'), ('Functions and Graphing', 'Functions and Graphing'), ('Geometry and Spatial Reasoning', 'Geometry and Spatial Reasoning'), ('Exponents, Powers, and Scientific Notation', 'Exponents, Powers, and Scientific Notation'), ('Polynomials', 'Polynomials'), ('Trigonometry', 'Trigonometry'), ('Statistics and Data Analysis', 'Statistics and Data Analysis')], max_length=100),
        ),
    ]
