# Generated by Django 5.2.15 on 2026-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_update_post_testing_grade_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Whether this topic is visible to learners in the Topic Catalogue'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='grade_level_max',
            field=models.IntegerField(default=10, help_text='Maximum grade level (10)'),
        ),
    ]
